name: kokoroio
description: kokoro-io REST API client for dart.
version: 0.1.0
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_serializable: ^3.2.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.0.0
